// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8LPst-JO2Tkb6bPh8NrkT2EmLDraohuU',
    appId: '1:760177477560:web:f8f9c7f96765a03bfa714d',
    messagingSenderId: '760177477560',
    projectId: 'habitron-dev',
    authDomain: 'habitron-dev.firebaseapp.com',
    storageBucket: 'habitron-dev.firebasestorage.app',
    measurementId: 'G-K82ZX41YE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfeVRCNWoeDWCdBExUY0LcNpKjmgZj6A',
    appId: '1:760177477560:android:d6507650fe91b3c1fa714d',
    messagingSenderId: '760177477560',
    projectId: 'habitron-dev',
    storageBucket: 'habitron-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtS0WF_fv6QuZOtRYMa1OsO0fKsRSjPS0',
    appId: '1:760177477560:ios:db0f64a94e898850fa714d',
    messagingSenderId: '760177477560',
    projectId: 'habitron-dev',
    storageBucket: 'habitron-dev.firebasestorage.app',
    iosClientId: '760177477560-mkiakckhqvocahjq71e7c66ta4pt3irh.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtS0WF_fv6QuZOtRYMa1OsO0fKsRSjPS0',
    appId: '1:760177477560:ios:db0f64a94e898850fa714d',
    messagingSenderId: '760177477560',
    projectId: 'habitron-dev',
    storageBucket: 'habitron-dev.firebasestorage.app',
    iosClientId: '760177477560-mkiakckhqvocahjq71e7c66ta4pt3irh.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8LPst-JO2Tkb6bPh8NrkT2EmLDraohuU',
    appId: '1:760177477560:web:62b05c6c870839a1fa714d',
    messagingSenderId: '760177477560',
    projectId: 'habitron-dev',
    authDomain: 'habitron-dev.firebaseapp.com',
    storageBucket: 'habitron-dev.firebasestorage.app',
    measurementId: 'G-HCS4PCMH6K',
  );
}
